pipeline{
    agent any
    stages {
        stage('Build') {
            steps {
                sh '''
                    ./jenkins/build/mvn.sh mvn -B -DskipTests clean package
                    ./jenkins/build/build.sh

                   '''
             }
        } 
        stage('test') {
            steps {
                sh '''
                    ./jenkins/build/mvn.sh mvn test
                   '''
            }
        }
        stage('push') {
            steps {
                sh '''
                    ./jenkins/push/push.sh
                   '''
            }
        }
        stage('deploy') {
            steps {
                sh '''
                    ./jenkins/push/push.sh
                   '''
            }
        }
    }   
        
    
}
